-- 商家分佣与结算报表 MVP 新增表
-- 仅新增本模块 4 张表及索引，不涉及现有表结构变更

-- 商家分佣/服务结算规则
CREATE TABLE `merchant_commission_rules` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `rule_type` VARCHAR(30) NOT NULL,
  `merchant_promotion_source_id` BIGINT NULL,
  `pickup_store_id` BIGINT NULL,
  `benefit_package_id` BIGINT NULL,
  `benefit_package_item_id` BIGINT NULL,
  `calculation_type` VARCHAR(20) NOT NULL,
  `commission_rate` INT NULL,
  `commission_amount` INT NULL,
  `min_commission_amount` INT NULL,
  `max_commission_amount` INT NULL,
  `effective_start_at` DATETIME(3) NULL,
  `effective_end_at` DATETIME(3) NULL,
  `status` INT NOT NULL DEFAULT 1,
  `priority` INT NOT NULL DEFAULT 0,
  `remark` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  INDEX `idx_commission_rule_rule_type` (`rule_type`),
  INDEX `idx_commission_rule_merchant` (`merchant_promotion_source_id`),
  INDEX `idx_commission_rule_store` (`pickup_store_id`),
  INDEX `idx_commission_rule_package` (`benefit_package_id`),
  INDEX `idx_commission_rule_package_item` (`benefit_package_item_id`),
  INDEX `idx_commission_rule_status` (`status`),
  INDEX `idx_commission_rule_priority` (`priority`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 商家分佣/服务结算明细
CREATE TABLE `merchant_commission_records` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `rule_id` BIGINT NULL,
  `merchant_promotion_source_id` BIGINT NULL,
  `pickup_store_id` BIGINT NULL,
  `user_id` BIGINT NULL,
  `order_id` BIGINT NULL,
  `order_item_id` BIGINT NULL,
  `benefit_package_id` BIGINT NULL,
  `benefit_package_item_id` BIGINT NULL,
  `entitlement_id` BIGINT NULL,
  `verification_log_id` BIGINT NULL,
  `source_type` VARCHAR(30) NOT NULL,
  `source_amount` INT NOT NULL DEFAULT 0,
  `commission_amount` INT NOT NULL DEFAULT 0,
  `calculation_snapshot` JSON NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `dedupe_key` VARCHAR(150) NOT NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `confirmed_at` DATETIME(3) NULL,
  `settled_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `remark` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  UNIQUE INDEX `merchant_commission_records_dedupe_key_key` (`dedupe_key`),
  INDEX `idx_commission_record_rule_id` (`rule_id`),
  INDEX `idx_commission_record_merchant` (`merchant_promotion_source_id`),
  INDEX `idx_commission_record_store` (`pickup_store_id`),
  INDEX `idx_commission_record_order_id` (`order_id`),
  INDEX `idx_commission_record_verify_log_id` (`verification_log_id`),
  INDEX `idx_commission_record_source_type` (`source_type`),
  INDEX `idx_commission_record_status` (`status`),
  INDEX `idx_commission_record_occurred_at` (`occurred_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 结算批次
CREATE TABLE `merchant_settlement_batches` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `settlement_no` VARCHAR(32) NOT NULL,
  `merchant_promotion_source_id` BIGINT NULL,
  `pickup_store_id` BIGINT NULL,
  `period_start` DATETIME(3) NOT NULL,
  `period_end` DATETIME(3) NOT NULL,
  `record_count` INT NOT NULL DEFAULT 0,
  `total_source_amount` INT NOT NULL DEFAULT 0,
  `total_commission_amount` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
  `generated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `confirmed_at` DATETIME(3) NULL,
  `paid_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `remark` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `deleted_at` DATETIME(3) NULL,
  UNIQUE INDEX `merchant_settlement_batches_settlement_no_key` (`settlement_no`),
  INDEX `uk_settlement_no` (`settlement_no`),
  INDEX `idx_settlement_batch_merchant` (`merchant_promotion_source_id`),
  INDEX `idx_settlement_batch_store` (`pickup_store_id`),
  INDEX `idx_settlement_batch_period_start` (`period_start`),
  INDEX `idx_settlement_batch_period_end` (`period_end`),
  INDEX `idx_settlement_batch_status` (`status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 结算批次明细关联
CREATE TABLE `merchant_settlement_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT NOT NULL,
  `commission_record_id` BIGINT NOT NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `status` VARCHAR(20) NOT NULL DEFAULT 'included',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `merchant_settlement_items_commission_record_id_key` (`commission_record_id`),
  INDEX `idx_settlement_item_batch_id` (`batch_id`),
  INDEX `uk_settlement_item_record` (`commission_record_id`),
  INDEX `idx_settlement_item_status` (`status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
