packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - 'bcrypt'
  - 'core-js'
  - 'core-js-pure'
  - 'esbuild'
  - 'prisma'
  - 'vue-demi'
